name: Deploy prod
on:
  push:
    branches:
    - env/live

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML==5.3.1
        pip install awsebcli --upgrade --user
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION="us-east-1"
        eb init --region us-east-1 --platform "arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.8 running on 64bit Amazon Linux 2/3.5.4" streetlives_v2
        eb deploy yourpeer-env-live --timeout 20
